[tool.poetry]
description = "Python environment for Advent of Code 2024"
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
pyyaml = "^6.0"
deepdiff = "^6.3.0"
numpy = "2.2.1"
black = "24.10.0"
